{
    'name': 'ILO Farming Perspective',
    'version': '1.0',
    'depends': [
        'base',
        'sale',
        'stock',
        'project',
        'hr',
        'mrp',
        'web',
        'contacts',
        'uom',
        'grt_image_url',
        'grt_l10n_id_kabupaten',
          # Add this line to depend on the uom module
    ],
    'author': 'Ali Shidqie Al Faruqi',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/ilo_assets_views.xml',
        'views/ilo_farming_menus.xml',
        'views/inherited_custom_views.xml',
        'views/ilo_dashboard_views.xml',
        'views/qr_code_views.xml',
        'views/transactional_views.xml',
        'views/ilo_produksi_views.xml',
        # 'views/ilo_farmer_views.xml',
        'views/ilo_inventory_views.xml',
        'views/ilo_quant_views.xml',
        'views/ilo_stock_location_views.xml',
        'views/ilo_stock_move_views.xml',
        'views/ilo_warehouse_views.xml',
        'views/ilo_production_planting.xml',
        'views/ilo_production_hasil_views.xml',
        'views/ilo_production_monitoring_views.xml',
        'views/ilo_transactional_monitoring.xml',
        'views/ilo_reference_views.xml',
        'views/ilo_product_history.xml',
        'data/ir_sequence_data.xml',
        'data/ilo_sequence_data.xml',
        'data/ilo_farmer_sequence.xml',
    ],
    'installable': True,
    'application': True,
}
